# Generated by Django 3.0.8 on 2023-11-18 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_ADDED_COLUMN_NAME_RATING'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='type_of_illness',
            field=models.CharField(default='Allergies', max_length=80),
        ),
        migrations.AlterField(
            model_name='product',
            name='rating',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
