# Generated by Django 3.0.8 on 2023-11-18 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_ADDED_NEW_COLUMN_type_of_illness'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='type_of_illness',
            new_name='subcategory',
        ),
    ]
