# Generated by Django 3.0.8 on 2023-12-01 22:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0020_remove_product_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order_Addr_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('phone_number', models.CharField(max_length=100)),
                ('shipping_address', models.CharField(max_length=200, null=True)),
                ('city', models.CharField(max_length=200, null=True)),
                ('state', models.CharField(max_length=200, null=True)),
                ('country', models.CharField(max_length=100, null=True)),
                ('zipcode', models.CharField(max_length=200, null=True)),
                ('amount', models.IntegerField(blank=True, null=True)),
                ('transaction_id', models.CharField(max_length=100, null=True)),
                ('date_ordered', models.DateTimeField(auto_now_add=True, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Shipping_Addresse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('phone_number', models.CharField(max_length=100)),
                ('shipping_address', models.CharField(max_length=200, null=True)),
                ('city', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=100, null=True)),
                ('zipcode', models.CharField(max_length=200)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RenameModel(
            old_name='OrderItem',
            new_name='Cart_Item',
        ),
        migrations.RemoveField(
            model_name='fullorder',
            name='user',
        ),
        migrations.DeleteModel(
            name='ShippingAddress',
        ),
        migrations.AlterField(
            model_name='purchased_item',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='store.Order_Addr_info'),
        ),
        migrations.DeleteModel(
            name='FullOrder',
        ),
    ]
