# Generated by Django 3.0.8 on 2023-12-01 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0021_auto_20231201_1924'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchased_item',
            name='description',
        ),
    ]
