# Generated by Django 3.0.8 on 2023-12-01 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0022_remove_purchased_item_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchased_item',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
